### ISSUE TITLE
2022年解析 所属 书籍or平台

### ISSUE THREAD

**Issue by mendge** [YiBin16/KaoYan-Math_1#1]
**2022年解析**感觉不错，想买纸质，请问作者知道所属的书籍或者平台么？

**Comment by JimmyKudo16** [comment]
淘宝各大书店搜索考研数学一真题均有纸质版可购买

**Comment by mendge** [comment]
不，各种解析是不同啊，你的仓库21年和22年的解析风格和解析深度就不同，我想知道22年的解析的源书籍或者源平台？请问作者知道吗？

**Comment by JimmyKudo16** [comment]
那你可以直接拿这个去打印
我也不记得在哪里找的资源了
